#%RAML 1.0
title: Sample API
/train:
  get:
    responses:
      '200':
        description: All Customers
        body:
          application/json: 
            example: {"":""}
  post:
    body:
      application/json:
        example: { "":"" }
    responses:
      '200':
        body:
          application/json:
            example:
              {"Status": "Added"}  
  put:
      responses: 
        '200':
          description: Get specific customer details
          body: 
            application/json: 
              example:
                custName: "Deepanshu Deshmukh"
                custId: "112"
              type: object
  delete:
      body: 
        application/json: 
          example: { "":"" }
      responses: 
        '200':
          body: 
            application/json: 
              example: {"Status": "Deleted"}                                      