#%RAML 1.0
title: Sample API
/train:
  get:
    responses:
      '200':
        description: All Customers
        body:
          application/json: 
            example: { "trainno": "", "TrainName": "", "TravelDays": "", "From": "", "Destination": "", "Time": "" }
  post:
    body:
      application/json:
        example: { "trainno": "", "TrainName": "", "TravelDays": "", "From": "", "Destination": "", "Time": "" }
    responses:
      '200':
        body:
          application/json:
            example:
              {"Status": "Added"}  
  put:
      body: 
        application/json: 
          example: { "trainno": "", "TrainName": "", "TravelDays": "", "From": "", "Destination": "", "Time": "" }
      responses: 
        '200':
          description: Update Train Details
          body: 
            application/json: 
              example: {"Status": "Updated"}
  delete:
      body: 
        application/json: 
          example: { "":"" }
      responses: 
        '200':
          body: 
            application/json: 
              example: {"Status": "Deleted"}                                      